// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "normalizeHisto0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic normalizeHisto0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic normalizeHisto0::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> normalizeHisto0::ap_ST_fsm_state1 = "1";
const sc_lv<3> normalizeHisto0::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> normalizeHisto0::ap_ST_fsm_state13 = "100";
const bool normalizeHisto0::ap_const_boolean_1 = true;
const sc_lv<32> normalizeHisto0::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> normalizeHisto0::ap_const_lv1_1 = "1";
const sc_lv<32> normalizeHisto0::ap_const_lv32_1 = "1";
const sc_lv<1> normalizeHisto0::ap_const_lv1_0 = "0";
const sc_lv<7> normalizeHisto0::ap_const_lv7_0 = "0000000";
const sc_lv<2> normalizeHisto0::ap_const_lv2_0 = "00";
const sc_lv<6> normalizeHisto0::ap_const_lv6_0 = "000000";
const sc_lv<10> normalizeHisto0::ap_const_lv10_66 = "1100110";
const sc_lv<10> normalizeHisto0::ap_const_lv10_99 = "10011001";
const sc_lv<10> normalizeHisto0::ap_const_lv10_CC = "11001100";
const sc_lv<10> normalizeHisto0::ap_const_lv10_100 = "100000000";
const sc_lv<10> normalizeHisto0::ap_const_lv10_133 = "100110011";
const sc_lv<10> normalizeHisto0::ap_const_lv10_166 = "101100110";
const sc_lv<10> normalizeHisto0::ap_const_lv10_199 = "110011001";
const sc_lv<7> normalizeHisto0::ap_const_lv7_48 = "1001000";
const sc_lv<7> normalizeHisto0::ap_const_lv7_1 = "1";
const sc_lv<6> normalizeHisto0::ap_const_lv6_24 = "100100";
const sc_lv<2> normalizeHisto0::ap_const_lv2_1 = "1";
const sc_lv<6> normalizeHisto0::ap_const_lv6_1 = "1";
const sc_lv<65> normalizeHisto0::ap_const_lv65_1C71C71C8 = "111000111000111000111000111001000";
const sc_lv<5> normalizeHisto0::ap_const_lv5_0 = "00000";
const sc_lv<32> normalizeHisto0::ap_const_lv32_26 = "100110";
const sc_lv<32> normalizeHisto0::ap_const_lv32_40 = "1000000";
const sc_lv<3> normalizeHisto0::ap_const_lv3_0 = "000";
const sc_lv<32> normalizeHisto0::ap_const_lv32_2 = "10";
const sc_lv<32> normalizeHisto0::ap_const_lv32_1E = "11110";
const sc_lv<32> normalizeHisto0::ap_const_lv32_1D = "11101";
const sc_lv<32> normalizeHisto0::ap_const_lv32_27 = "100111";
const sc_lv<32> normalizeHisto0::ap_const_lv32_28 = "101000";
const sc_lv<10> normalizeHisto0::ap_const_lv10_33 = "110011";
const sc_lv<10> normalizeHisto0::ap_const_lv10_0 = "0000000000";

normalizeHisto0::normalizeHisto0(sc_module_name name) : sc_module(name), mVcdFile(0) {
    hog_mul_34ns_32nsjbC_U45 = new hog_mul_34ns_32nsjbC<1,7,34,32,65>("hog_mul_34ns_32nsjbC_U45");
    hog_mul_34ns_32nsjbC_U45->clk(ap_clk);
    hog_mul_34ns_32nsjbC_U45->reset(ap_rst);
    hog_mul_34ns_32nsjbC_U45->din0(grp_fu_301_p0);
    hog_mul_34ns_32nsjbC_U45->din1(grp_fu_301_p1);
    hog_mul_34ns_32nsjbC_U45->ce(ap_var_for_const0);
    hog_mul_34ns_32nsjbC_U45->dout(grp_fu_301_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_condition_199);
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( tmp_26_reg_685 );
    sensitive << ( tmp_28_reg_689 );
    sensitive << ( tmp_29_reg_693 );
    sensitive << ( tmp_31_reg_697 );
    sensitive << ( tmp_32_reg_701 );

    SC_METHOD(thread_ap_condition_203);
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( tmp_26_reg_685 );
    sensitive << ( tmp_28_reg_689 );
    sensitive << ( tmp_29_reg_693 );
    sensitive << ( tmp_31_reg_697 );
    sensitive << ( tmp_32_reg_701 );

    SC_METHOD(thread_ap_condition_207);
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( tmp_26_reg_685 );
    sensitive << ( tmp_28_reg_689 );
    sensitive << ( tmp_29_reg_693 );
    sensitive << ( tmp_31_reg_697 );

    SC_METHOD(thread_ap_condition_211);
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( tmp_26_reg_685 );
    sensitive << ( tmp_28_reg_689 );
    sensitive << ( tmp_29_reg_693 );

    SC_METHOD(thread_ap_condition_215);
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( tmp_26_reg_685 );
    sensitive << ( tmp_28_reg_689 );

    SC_METHOD(thread_ap_condition_219);
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( tmp_26_reg_685 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_average_cast7_fu_361_p1);
    sensitive << ( tmp_35_reg_650 );

    SC_METHOD(thread_average_cast8_fu_358_p1);
    sensitive << ( tmp_35_reg_650 );

    SC_METHOD(thread_average_cast_fu_364_p1);
    sensitive << ( tmp_35_reg_650 );

    SC_METHOD(thread_blkIdx_phi_fu_225_p4);
    sensitive << ( blkIdx_reg_221 );
    sensitive << ( exitcond_flatten_reg_598 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_mid2_v_reg_612 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_blkIdx_s_fu_269_p2);
    sensitive << ( blkIdx_phi_fu_225_p4 );

    SC_METHOD(thread_descriptor_V_address0);
    sensitive << ( tmp_21_fu_353_p1 );
    sensitive << ( ap_enable_reg_pp0_iter8 );

    SC_METHOD(thread_descriptor_V_ce0);
    sensitive << ( ap_enable_reg_pp0_iter8 );

    SC_METHOD(thread_exitcond_flatten_fu_243_p2);
    sensitive << ( indvar_flatten_reg_210 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_301_p0);
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_grp_fu_301_p1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( grp_fu_301_p10 );

    SC_METHOD(thread_grp_fu_301_p10);
    sensitive << ( sum_q0 );

    SC_METHOD(thread_i_2_fu_287_p2);
    sensitive << ( i_mid2_fu_261_p3 );

    SC_METHOD(thread_i_mid2_fu_261_p3);
    sensitive << ( i_reg_232 );
    sensitive << ( tmp_34_fu_255_p2 );

    SC_METHOD(thread_indvar_flatten_next_fu_249_p2);
    sensitive << ( indvar_flatten_reg_210 );

    SC_METHOD(thread_normalized_V_addr25_gep_fu_201_p3);
    sensitive << ( ap_pipeline_reg_pp0_iter9_tmp_21_reg_660 );
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_normalized_V_addr_10_gep_fu_165_p3);
    sensitive << ( ap_pipeline_reg_pp0_iter9_tmp_21_reg_660 );
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( tmp_26_reg_685 );
    sensitive << ( tmp_28_reg_689 );
    sensitive << ( tmp_29_reg_693 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_normalized_V_addr_11_gep_fu_156_p3);
    sensitive << ( ap_pipeline_reg_pp0_iter9_tmp_21_reg_660 );
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( tmp_26_reg_685 );
    sensitive << ( tmp_28_reg_689 );
    sensitive << ( tmp_29_reg_693 );
    sensitive << ( tmp_31_reg_697 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_normalized_V_addr_12_gep_fu_147_p3);
    sensitive << ( ap_pipeline_reg_pp0_iter9_tmp_21_reg_660 );
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( tmp_26_reg_685 );
    sensitive << ( tmp_28_reg_689 );
    sensitive << ( tmp_29_reg_693 );
    sensitive << ( tmp_31_reg_697 );
    sensitive << ( tmp_32_reg_701 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_normalized_V_addr_8_gep_fu_183_p3);
    sensitive << ( ap_pipeline_reg_pp0_iter9_tmp_21_reg_660 );
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( tmp_26_reg_685 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_normalized_V_addr_9_gep_fu_174_p3);
    sensitive << ( ap_pipeline_reg_pp0_iter9_tmp_21_reg_660 );
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( tmp_26_reg_685 );
    sensitive << ( tmp_28_reg_689 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_normalized_V_addr_gep_fu_192_p3);
    sensitive << ( ap_pipeline_reg_pp0_iter9_tmp_21_reg_660 );
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_normalized_V_address1);
    sensitive << ( ap_pipeline_reg_pp0_iter9_tmp_21_reg_660 );
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( normalized_V_addr_12_gep_fu_147_p3 );
    sensitive << ( normalized_V_addr_11_gep_fu_156_p3 );
    sensitive << ( normalized_V_addr_10_gep_fu_165_p3 );
    sensitive << ( normalized_V_addr_9_gep_fu_174_p3 );
    sensitive << ( normalized_V_addr_8_gep_fu_183_p3 );
    sensitive << ( normalized_V_addr_gep_fu_192_p3 );
    sensitive << ( normalized_V_addr25_gep_fu_201_p3 );
    sensitive << ( ap_condition_199 );
    sensitive << ( ap_condition_203 );
    sensitive << ( ap_condition_207 );
    sensitive << ( ap_condition_211 );
    sensitive << ( ap_condition_215 );
    sensitive << ( ap_condition_219 );

    SC_METHOD(thread_normalized_V_ce1);
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( tmp_26_reg_685 );
    sensitive << ( tmp_28_reg_689 );
    sensitive << ( tmp_29_reg_693 );
    sensitive << ( tmp_31_reg_697 );
    sensitive << ( tmp_32_reg_701 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_normalized_V_d1);
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( storemerge_cast_cast_fu_590_p3 );
    sensitive << ( ap_condition_199 );
    sensitive << ( ap_condition_203 );
    sensitive << ( ap_condition_207 );
    sensitive << ( ap_condition_211 );
    sensitive << ( ap_condition_215 );
    sensitive << ( ap_condition_219 );

    SC_METHOD(thread_normalized_V_we1);
    sensitive << ( tmp_22_reg_677 );
    sensitive << ( tmp_24_reg_681 );
    sensitive << ( tmp_26_reg_685 );
    sensitive << ( tmp_28_reg_689 );
    sensitive << ( tmp_29_reg_693 );
    sensitive << ( tmp_31_reg_697 );
    sensitive << ( tmp_32_reg_701 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_METHOD(thread_op2_assign_10_cast_fu_542_p1);
    sensitive << ( tmp_41_fu_538_p1 );

    SC_METHOD(thread_op2_assign_11_cast_fu_561_p1);
    sensitive << ( tmp_42_fu_552_p4 );

    SC_METHOD(thread_op2_assign_12_cast_fu_580_p1);
    sensitive << ( tmp_43_fu_571_p4 );

    SC_METHOD(thread_op2_assign_7_cast_fu_439_p1);
    sensitive << ( tmp_36_fu_435_p1 );

    SC_METHOD(thread_op2_assign_8_cast_fu_469_p1);
    sensitive << ( tmp_38_fu_465_p1 );

    SC_METHOD(thread_op2_assign_9_cast_fu_506_p1);
    sensitive << ( tmp_39_fu_496_p4 );

    SC_METHOD(thread_op2_assign_cast6_fu_374_p1);
    sensitive << ( op2_assign_fu_367_p3 );

    SC_METHOD(thread_op2_assign_cast_fu_378_p1);
    sensitive << ( op2_assign_fu_367_p3 );

    SC_METHOD(thread_op2_assign_fu_367_p3);
    sensitive << ( tmp_35_reg_650 );

    SC_METHOD(thread_p_shl4_cast_mid2_fu_314_p1);
    sensitive << ( p_shl4_cast_mid2_v_fu_307_p3 );

    SC_METHOD(thread_p_shl4_cast_mid2_v_fu_307_p3);
    sensitive << ( ap_pipeline_reg_pp0_iter6_tmp_reg_618 );

    SC_METHOD(thread_p_shl5_cast_fu_415_p1);
    sensitive << ( p_shl5_fu_408_p3 );

    SC_METHOD(thread_p_shl5_fu_408_p3);
    sensitive << ( tmp_35_reg_650 );

    SC_METHOD(thread_p_shl6_cast_fu_486_p1);
    sensitive << ( p_shl6_fu_479_p3 );

    SC_METHOD(thread_p_shl6_fu_479_p3);
    sensitive << ( tmp_35_reg_650 );

    SC_METHOD(thread_p_shl_cast_mid2_fu_330_p1);
    sensitive << ( p_shl_cast_mid2_v_fu_323_p3 );

    SC_METHOD(thread_p_shl_cast_mid2_v_fu_323_p3);
    sensitive << ( ap_pipeline_reg_pp0_iter7_tmp_reg_618 );

    SC_METHOD(thread_storemerge_cast_cast_fu_590_p3);
    sensitive << ( tmp_33_reg_705 );

    SC_METHOD(thread_sum_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_mid2_fu_293_p1 );

    SC_METHOD(thread_sum_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_tmp1_cast_fu_344_p1);
    sensitive << ( tmp1_reg_639 );

    SC_METHOD(thread_tmp1_fu_318_p2);
    sensitive << ( ap_pipeline_reg_pp0_iter6_i_mid2_reg_607 );
    sensitive << ( p_shl4_cast_mid2_fu_314_p1 );

    SC_METHOD(thread_tmp_20_fu_347_p2);
    sensitive << ( p_shl_cast_mid2_fu_330_p1 );
    sensitive << ( tmp1_cast_fu_344_p1 );

    SC_METHOD(thread_tmp_21_fu_353_p1);
    sensitive << ( tmp_20_fu_347_p2 );

    SC_METHOD(thread_tmp_22_cast2_fu_394_p1);
    sensitive << ( descriptor_V_q0 );

    SC_METHOD(thread_tmp_22_cast3_fu_390_p1);
    sensitive << ( descriptor_V_q0 );

    SC_METHOD(thread_tmp_22_cast4_fu_386_p1);
    sensitive << ( descriptor_V_q0 );

    SC_METHOD(thread_tmp_22_cast5_fu_382_p1);
    sensitive << ( descriptor_V_q0 );

    SC_METHOD(thread_tmp_22_cast_fu_398_p1);
    sensitive << ( descriptor_V_q0 );

    SC_METHOD(thread_tmp_22_fu_402_p2);
    sensitive << ( ap_pipeline_reg_pp0_iter8_exitcond_flatten_reg_598 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( tmp_22_cast_fu_398_p1 );
    sensitive << ( op2_assign_cast_fu_378_p1 );

    SC_METHOD(thread_tmp_23_fu_419_p2);
    sensitive << ( p_shl5_cast_fu_415_p1 );
    sensitive << ( average_cast8_fu_358_p1 );

    SC_METHOD(thread_tmp_24_fu_443_p2);
    sensitive << ( tmp_22_fu_402_p2 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( tmp_22_cast2_fu_394_p1 );
    sensitive << ( op2_assign_7_cast_fu_439_p1 );

    SC_METHOD(thread_tmp_25_fu_449_p2);
    sensitive << ( p_shl5_cast_fu_415_p1 );
    sensitive << ( op2_assign_cast6_fu_374_p1 );

    SC_METHOD(thread_tmp_26_fu_473_p2);
    sensitive << ( tmp_22_fu_402_p2 );
    sensitive << ( tmp_24_fu_443_p2 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( tmp_22_cast2_fu_394_p1 );
    sensitive << ( op2_assign_8_cast_fu_469_p1 );

    SC_METHOD(thread_tmp_27_fu_490_p2);
    sensitive << ( p_shl6_cast_fu_486_p1 );
    sensitive << ( average_cast7_fu_361_p1 );

    SC_METHOD(thread_tmp_28_fu_510_p2);
    sensitive << ( tmp_22_fu_402_p2 );
    sensitive << ( tmp_24_fu_443_p2 );
    sensitive << ( tmp_26_fu_473_p2 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( tmp_22_cast_fu_398_p1 );
    sensitive << ( op2_assign_9_cast_fu_506_p1 );

    SC_METHOD(thread_tmp_29_fu_516_p2);
    sensitive << ( tmp_22_fu_402_p2 );
    sensitive << ( tmp_24_fu_443_p2 );
    sensitive << ( tmp_26_fu_473_p2 );
    sensitive << ( tmp_28_fu_510_p2 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( tmp_22_cast3_fu_390_p1 );
    sensitive << ( average_cast_fu_364_p1 );

    SC_METHOD(thread_tmp_30_fu_522_p2);
    sensitive << ( p_shl6_cast_fu_486_p1 );
    sensitive << ( average_cast7_fu_361_p1 );

    SC_METHOD(thread_tmp_31_fu_546_p2);
    sensitive << ( tmp_22_fu_402_p2 );
    sensitive << ( tmp_24_fu_443_p2 );
    sensitive << ( tmp_26_fu_473_p2 );
    sensitive << ( tmp_28_fu_510_p2 );
    sensitive << ( tmp_29_fu_516_p2 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( tmp_22_cast2_fu_394_p1 );
    sensitive << ( op2_assign_10_cast_fu_542_p1 );

    SC_METHOD(thread_tmp_32_fu_565_p2);
    sensitive << ( tmp_22_fu_402_p2 );
    sensitive << ( tmp_24_fu_443_p2 );
    sensitive << ( tmp_26_fu_473_p2 );
    sensitive << ( tmp_28_fu_510_p2 );
    sensitive << ( tmp_29_fu_516_p2 );
    sensitive << ( tmp_31_fu_546_p2 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( tmp_22_cast4_fu_386_p1 );
    sensitive << ( op2_assign_11_cast_fu_561_p1 );

    SC_METHOD(thread_tmp_33_fu_584_p2);
    sensitive << ( tmp_22_fu_402_p2 );
    sensitive << ( tmp_24_fu_443_p2 );
    sensitive << ( tmp_26_fu_473_p2 );
    sensitive << ( tmp_28_fu_510_p2 );
    sensitive << ( tmp_29_fu_516_p2 );
    sensitive << ( tmp_31_fu_546_p2 );
    sensitive << ( tmp_32_fu_565_p2 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( tmp_22_cast5_fu_382_p1 );
    sensitive << ( op2_assign_12_cast_fu_580_p1 );

    SC_METHOD(thread_tmp_34_fu_255_p2);
    sensitive << ( i_reg_232 );
    sensitive << ( exitcond_flatten_fu_243_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_36_fu_435_p1);
    sensitive << ( tmp_s_fu_425_p4 );

    SC_METHOD(thread_tmp_37_fu_455_p4);
    sensitive << ( tmp_25_fu_449_p2 );

    SC_METHOD(thread_tmp_38_fu_465_p1);
    sensitive << ( tmp_37_fu_455_p4 );

    SC_METHOD(thread_tmp_39_fu_496_p4);
    sensitive << ( tmp_27_fu_490_p2 );

    SC_METHOD(thread_tmp_40_fu_528_p4);
    sensitive << ( tmp_30_fu_522_p2 );

    SC_METHOD(thread_tmp_41_fu_538_p1);
    sensitive << ( tmp_40_fu_528_p4 );

    SC_METHOD(thread_tmp_42_fu_552_p4);
    sensitive << ( mul_reg_644 );

    SC_METHOD(thread_tmp_43_fu_571_p4);
    sensitive << ( mul_reg_644 );

    SC_METHOD(thread_tmp_fu_283_p1);
    sensitive << ( tmp_mid2_v_fu_275_p3 );

    SC_METHOD(thread_tmp_mid2_fu_293_p1);
    sensitive << ( tmp_mid2_v_reg_612 );

    SC_METHOD(thread_tmp_mid2_v_fu_275_p3);
    sensitive << ( blkIdx_phi_fu_225_p4 );
    sensitive << ( tmp_34_fu_255_p2 );
    sensitive << ( blkIdx_s_fu_269_p2 );

    SC_METHOD(thread_tmp_s_fu_425_p4);
    sensitive << ( tmp_23_fu_419_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_flatten_fu_243_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "normalizeHisto0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, sum_address0, "(port)sum_address0");
    sc_trace(mVcdFile, sum_ce0, "(port)sum_ce0");
    sc_trace(mVcdFile, sum_q0, "(port)sum_q0");
    sc_trace(mVcdFile, descriptor_V_address0, "(port)descriptor_V_address0");
    sc_trace(mVcdFile, descriptor_V_ce0, "(port)descriptor_V_ce0");
    sc_trace(mVcdFile, descriptor_V_q0, "(port)descriptor_V_q0");
    sc_trace(mVcdFile, normalized_V_address1, "(port)normalized_V_address1");
    sc_trace(mVcdFile, normalized_V_ce1, "(port)normalized_V_ce1");
    sc_trace(mVcdFile, normalized_V_we1, "(port)normalized_V_we1");
    sc_trace(mVcdFile, normalized_V_d1, "(port)normalized_V_d1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten_reg_210, "indvar_flatten_reg_210");
    sc_trace(mVcdFile, blkIdx_reg_221, "blkIdx_reg_221");
    sc_trace(mVcdFile, i_reg_232, "i_reg_232");
    sc_trace(mVcdFile, exitcond_flatten_fu_243_p2, "exitcond_flatten_fu_243_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_598, "exitcond_flatten_reg_598");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_598, "ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_598");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter2_exitcond_flatten_reg_598, "ap_pipeline_reg_pp0_iter2_exitcond_flatten_reg_598");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter3_exitcond_flatten_reg_598, "ap_pipeline_reg_pp0_iter3_exitcond_flatten_reg_598");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter4_exitcond_flatten_reg_598, "ap_pipeline_reg_pp0_iter4_exitcond_flatten_reg_598");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter5_exitcond_flatten_reg_598, "ap_pipeline_reg_pp0_iter5_exitcond_flatten_reg_598");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter6_exitcond_flatten_reg_598, "ap_pipeline_reg_pp0_iter6_exitcond_flatten_reg_598");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter7_exitcond_flatten_reg_598, "ap_pipeline_reg_pp0_iter7_exitcond_flatten_reg_598");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter8_exitcond_flatten_reg_598, "ap_pipeline_reg_pp0_iter8_exitcond_flatten_reg_598");
    sc_trace(mVcdFile, indvar_flatten_next_fu_249_p2, "indvar_flatten_next_fu_249_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, i_mid2_fu_261_p3, "i_mid2_fu_261_p3");
    sc_trace(mVcdFile, i_mid2_reg_607, "i_mid2_reg_607");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter1_i_mid2_reg_607, "ap_pipeline_reg_pp0_iter1_i_mid2_reg_607");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter2_i_mid2_reg_607, "ap_pipeline_reg_pp0_iter2_i_mid2_reg_607");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter3_i_mid2_reg_607, "ap_pipeline_reg_pp0_iter3_i_mid2_reg_607");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter4_i_mid2_reg_607, "ap_pipeline_reg_pp0_iter4_i_mid2_reg_607");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter5_i_mid2_reg_607, "ap_pipeline_reg_pp0_iter5_i_mid2_reg_607");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter6_i_mid2_reg_607, "ap_pipeline_reg_pp0_iter6_i_mid2_reg_607");
    sc_trace(mVcdFile, tmp_mid2_v_fu_275_p3, "tmp_mid2_v_fu_275_p3");
    sc_trace(mVcdFile, tmp_mid2_v_reg_612, "tmp_mid2_v_reg_612");
    sc_trace(mVcdFile, tmp_fu_283_p1, "tmp_fu_283_p1");
    sc_trace(mVcdFile, tmp_reg_618, "tmp_reg_618");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter1_tmp_reg_618, "ap_pipeline_reg_pp0_iter1_tmp_reg_618");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter2_tmp_reg_618, "ap_pipeline_reg_pp0_iter2_tmp_reg_618");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter3_tmp_reg_618, "ap_pipeline_reg_pp0_iter3_tmp_reg_618");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter4_tmp_reg_618, "ap_pipeline_reg_pp0_iter4_tmp_reg_618");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter5_tmp_reg_618, "ap_pipeline_reg_pp0_iter5_tmp_reg_618");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter6_tmp_reg_618, "ap_pipeline_reg_pp0_iter6_tmp_reg_618");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter7_tmp_reg_618, "ap_pipeline_reg_pp0_iter7_tmp_reg_618");
    sc_trace(mVcdFile, i_2_fu_287_p2, "i_2_fu_287_p2");
    sc_trace(mVcdFile, tmp1_fu_318_p2, "tmp1_fu_318_p2");
    sc_trace(mVcdFile, tmp1_reg_639, "tmp1_reg_639");
    sc_trace(mVcdFile, grp_fu_301_p2, "grp_fu_301_p2");
    sc_trace(mVcdFile, mul_reg_644, "mul_reg_644");
    sc_trace(mVcdFile, tmp_35_reg_650, "tmp_35_reg_650");
    sc_trace(mVcdFile, tmp_21_fu_353_p1, "tmp_21_fu_353_p1");
    sc_trace(mVcdFile, tmp_21_reg_660, "tmp_21_reg_660");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter9_tmp_21_reg_660, "ap_pipeline_reg_pp0_iter9_tmp_21_reg_660");
    sc_trace(mVcdFile, tmp_22_fu_402_p2, "tmp_22_fu_402_p2");
    sc_trace(mVcdFile, tmp_22_reg_677, "tmp_22_reg_677");
    sc_trace(mVcdFile, tmp_24_fu_443_p2, "tmp_24_fu_443_p2");
    sc_trace(mVcdFile, tmp_24_reg_681, "tmp_24_reg_681");
    sc_trace(mVcdFile, tmp_26_fu_473_p2, "tmp_26_fu_473_p2");
    sc_trace(mVcdFile, tmp_26_reg_685, "tmp_26_reg_685");
    sc_trace(mVcdFile, tmp_28_fu_510_p2, "tmp_28_fu_510_p2");
    sc_trace(mVcdFile, tmp_28_reg_689, "tmp_28_reg_689");
    sc_trace(mVcdFile, tmp_29_fu_516_p2, "tmp_29_fu_516_p2");
    sc_trace(mVcdFile, tmp_29_reg_693, "tmp_29_reg_693");
    sc_trace(mVcdFile, tmp_31_fu_546_p2, "tmp_31_fu_546_p2");
    sc_trace(mVcdFile, tmp_31_reg_697, "tmp_31_reg_697");
    sc_trace(mVcdFile, tmp_32_fu_565_p2, "tmp_32_fu_565_p2");
    sc_trace(mVcdFile, tmp_32_reg_701, "tmp_32_reg_701");
    sc_trace(mVcdFile, tmp_33_fu_584_p2, "tmp_33_fu_584_p2");
    sc_trace(mVcdFile, tmp_33_reg_705, "tmp_33_reg_705");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, blkIdx_phi_fu_225_p4, "blkIdx_phi_fu_225_p4");
    sc_trace(mVcdFile, tmp_mid2_fu_293_p1, "tmp_mid2_fu_293_p1");
    sc_trace(mVcdFile, normalized_V_addr_12_gep_fu_147_p3, "normalized_V_addr_12_gep_fu_147_p3");
    sc_trace(mVcdFile, normalized_V_addr_11_gep_fu_156_p3, "normalized_V_addr_11_gep_fu_156_p3");
    sc_trace(mVcdFile, normalized_V_addr_10_gep_fu_165_p3, "normalized_V_addr_10_gep_fu_165_p3");
    sc_trace(mVcdFile, normalized_V_addr_9_gep_fu_174_p3, "normalized_V_addr_9_gep_fu_174_p3");
    sc_trace(mVcdFile, normalized_V_addr_8_gep_fu_183_p3, "normalized_V_addr_8_gep_fu_183_p3");
    sc_trace(mVcdFile, normalized_V_addr_gep_fu_192_p3, "normalized_V_addr_gep_fu_192_p3");
    sc_trace(mVcdFile, normalized_V_addr25_gep_fu_201_p3, "normalized_V_addr25_gep_fu_201_p3");
    sc_trace(mVcdFile, storemerge_cast_cast_fu_590_p3, "storemerge_cast_cast_fu_590_p3");
    sc_trace(mVcdFile, tmp_34_fu_255_p2, "tmp_34_fu_255_p2");
    sc_trace(mVcdFile, blkIdx_s_fu_269_p2, "blkIdx_s_fu_269_p2");
    sc_trace(mVcdFile, grp_fu_301_p0, "grp_fu_301_p0");
    sc_trace(mVcdFile, grp_fu_301_p1, "grp_fu_301_p1");
    sc_trace(mVcdFile, p_shl4_cast_mid2_v_fu_307_p3, "p_shl4_cast_mid2_v_fu_307_p3");
    sc_trace(mVcdFile, p_shl4_cast_mid2_fu_314_p1, "p_shl4_cast_mid2_fu_314_p1");
    sc_trace(mVcdFile, p_shl_cast_mid2_v_fu_323_p3, "p_shl_cast_mid2_v_fu_323_p3");
    sc_trace(mVcdFile, p_shl_cast_mid2_fu_330_p1, "p_shl_cast_mid2_fu_330_p1");
    sc_trace(mVcdFile, tmp1_cast_fu_344_p1, "tmp1_cast_fu_344_p1");
    sc_trace(mVcdFile, tmp_20_fu_347_p2, "tmp_20_fu_347_p2");
    sc_trace(mVcdFile, op2_assign_fu_367_p3, "op2_assign_fu_367_p3");
    sc_trace(mVcdFile, tmp_22_cast_fu_398_p1, "tmp_22_cast_fu_398_p1");
    sc_trace(mVcdFile, op2_assign_cast_fu_378_p1, "op2_assign_cast_fu_378_p1");
    sc_trace(mVcdFile, p_shl5_fu_408_p3, "p_shl5_fu_408_p3");
    sc_trace(mVcdFile, p_shl5_cast_fu_415_p1, "p_shl5_cast_fu_415_p1");
    sc_trace(mVcdFile, average_cast8_fu_358_p1, "average_cast8_fu_358_p1");
    sc_trace(mVcdFile, tmp_23_fu_419_p2, "tmp_23_fu_419_p2");
    sc_trace(mVcdFile, tmp_s_fu_425_p4, "tmp_s_fu_425_p4");
    sc_trace(mVcdFile, tmp_36_fu_435_p1, "tmp_36_fu_435_p1");
    sc_trace(mVcdFile, tmp_22_cast2_fu_394_p1, "tmp_22_cast2_fu_394_p1");
    sc_trace(mVcdFile, op2_assign_7_cast_fu_439_p1, "op2_assign_7_cast_fu_439_p1");
    sc_trace(mVcdFile, op2_assign_cast6_fu_374_p1, "op2_assign_cast6_fu_374_p1");
    sc_trace(mVcdFile, tmp_25_fu_449_p2, "tmp_25_fu_449_p2");
    sc_trace(mVcdFile, tmp_37_fu_455_p4, "tmp_37_fu_455_p4");
    sc_trace(mVcdFile, tmp_38_fu_465_p1, "tmp_38_fu_465_p1");
    sc_trace(mVcdFile, op2_assign_8_cast_fu_469_p1, "op2_assign_8_cast_fu_469_p1");
    sc_trace(mVcdFile, p_shl6_fu_479_p3, "p_shl6_fu_479_p3");
    sc_trace(mVcdFile, p_shl6_cast_fu_486_p1, "p_shl6_cast_fu_486_p1");
    sc_trace(mVcdFile, average_cast7_fu_361_p1, "average_cast7_fu_361_p1");
    sc_trace(mVcdFile, tmp_27_fu_490_p2, "tmp_27_fu_490_p2");
    sc_trace(mVcdFile, tmp_39_fu_496_p4, "tmp_39_fu_496_p4");
    sc_trace(mVcdFile, op2_assign_9_cast_fu_506_p1, "op2_assign_9_cast_fu_506_p1");
    sc_trace(mVcdFile, tmp_22_cast3_fu_390_p1, "tmp_22_cast3_fu_390_p1");
    sc_trace(mVcdFile, average_cast_fu_364_p1, "average_cast_fu_364_p1");
    sc_trace(mVcdFile, tmp_30_fu_522_p2, "tmp_30_fu_522_p2");
    sc_trace(mVcdFile, tmp_40_fu_528_p4, "tmp_40_fu_528_p4");
    sc_trace(mVcdFile, tmp_41_fu_538_p1, "tmp_41_fu_538_p1");
    sc_trace(mVcdFile, op2_assign_10_cast_fu_542_p1, "op2_assign_10_cast_fu_542_p1");
    sc_trace(mVcdFile, tmp_42_fu_552_p4, "tmp_42_fu_552_p4");
    sc_trace(mVcdFile, tmp_22_cast4_fu_386_p1, "tmp_22_cast4_fu_386_p1");
    sc_trace(mVcdFile, op2_assign_11_cast_fu_561_p1, "op2_assign_11_cast_fu_561_p1");
    sc_trace(mVcdFile, tmp_43_fu_571_p4, "tmp_43_fu_571_p4");
    sc_trace(mVcdFile, tmp_22_cast5_fu_382_p1, "tmp_22_cast5_fu_382_p1");
    sc_trace(mVcdFile, op2_assign_12_cast_fu_580_p1, "op2_assign_12_cast_fu_580_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_301_p10, "grp_fu_301_p10");
    sc_trace(mVcdFile, ap_condition_199, "ap_condition_199");
    sc_trace(mVcdFile, ap_condition_203, "ap_condition_203");
    sc_trace(mVcdFile, ap_condition_207, "ap_condition_207");
    sc_trace(mVcdFile, ap_condition_211, "ap_condition_211");
    sc_trace(mVcdFile, ap_condition_215, "ap_condition_215");
    sc_trace(mVcdFile, ap_condition_219, "ap_condition_219");
#endif

    }
}

normalizeHisto0::~normalizeHisto0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete hog_mul_34ns_32nsjbC_U45;
}

void normalizeHisto0::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void normalizeHisto0::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
             !esl_seteq<1,1,1>(exitcond_flatten_fu_243_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(exitcond_flatten_fu_243_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                     !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
                    (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
                     !esl_seteq<1,1,1>(exitcond_flatten_fu_243_p2.read(), ap_const_lv1_0)))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter10 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_598.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        blkIdx_reg_221 = tmp_mid2_v_reg_612.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        blkIdx_reg_221 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_243_p2.read(), ap_const_lv1_0))) {
        i_reg_232 = i_2_fu_287_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_232 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_243_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_210 = indvar_flatten_next_fu_249_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar_flatten_reg_210 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()))) {
        ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_598 = exitcond_flatten_reg_598.read();
        ap_pipeline_reg_pp0_iter1_i_mid2_reg_607 = i_mid2_reg_607.read();
        ap_pipeline_reg_pp0_iter1_tmp_reg_618 = tmp_reg_618.read();
        exitcond_flatten_reg_598 = exitcond_flatten_fu_243_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
        ap_pipeline_reg_pp0_iter2_exitcond_flatten_reg_598 = ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_598.read();
        ap_pipeline_reg_pp0_iter2_i_mid2_reg_607 = ap_pipeline_reg_pp0_iter1_i_mid2_reg_607.read();
        ap_pipeline_reg_pp0_iter2_tmp_reg_618 = ap_pipeline_reg_pp0_iter1_tmp_reg_618.read();
        ap_pipeline_reg_pp0_iter3_exitcond_flatten_reg_598 = ap_pipeline_reg_pp0_iter2_exitcond_flatten_reg_598.read();
        ap_pipeline_reg_pp0_iter3_i_mid2_reg_607 = ap_pipeline_reg_pp0_iter2_i_mid2_reg_607.read();
        ap_pipeline_reg_pp0_iter3_tmp_reg_618 = ap_pipeline_reg_pp0_iter2_tmp_reg_618.read();
        ap_pipeline_reg_pp0_iter4_exitcond_flatten_reg_598 = ap_pipeline_reg_pp0_iter3_exitcond_flatten_reg_598.read();
        ap_pipeline_reg_pp0_iter4_i_mid2_reg_607 = ap_pipeline_reg_pp0_iter3_i_mid2_reg_607.read();
        ap_pipeline_reg_pp0_iter4_tmp_reg_618 = ap_pipeline_reg_pp0_iter3_tmp_reg_618.read();
        ap_pipeline_reg_pp0_iter5_exitcond_flatten_reg_598 = ap_pipeline_reg_pp0_iter4_exitcond_flatten_reg_598.read();
        ap_pipeline_reg_pp0_iter5_i_mid2_reg_607 = ap_pipeline_reg_pp0_iter4_i_mid2_reg_607.read();
        ap_pipeline_reg_pp0_iter5_tmp_reg_618 = ap_pipeline_reg_pp0_iter4_tmp_reg_618.read();
        ap_pipeline_reg_pp0_iter6_exitcond_flatten_reg_598 = ap_pipeline_reg_pp0_iter5_exitcond_flatten_reg_598.read();
        ap_pipeline_reg_pp0_iter6_i_mid2_reg_607 = ap_pipeline_reg_pp0_iter5_i_mid2_reg_607.read();
        ap_pipeline_reg_pp0_iter6_tmp_reg_618 = ap_pipeline_reg_pp0_iter5_tmp_reg_618.read();
        ap_pipeline_reg_pp0_iter7_exitcond_flatten_reg_598 = ap_pipeline_reg_pp0_iter6_exitcond_flatten_reg_598.read();
        ap_pipeline_reg_pp0_iter7_tmp_reg_618 = ap_pipeline_reg_pp0_iter6_tmp_reg_618.read();
        ap_pipeline_reg_pp0_iter8_exitcond_flatten_reg_598 = ap_pipeline_reg_pp0_iter7_exitcond_flatten_reg_598.read();
        ap_pipeline_reg_pp0_iter9_tmp_21_reg_660 = tmp_21_reg_660.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_243_p2.read(), ap_const_lv1_0))) {
        i_mid2_reg_607 = i_mid2_fu_261_p3.read();
        tmp_reg_618 = tmp_fu_283_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_pipeline_reg_pp0_iter7_exitcond_flatten_reg_598.read(), ap_const_lv1_0)) {
        mul_reg_644 = grp_fu_301_p2.read();
        tmp_21_reg_660 = tmp_21_fu_353_p1.read();
        tmp_35_reg_650 = grp_fu_301_p2.read().range(64, 38);
    }
    if (esl_seteq<1,1,1>(ap_pipeline_reg_pp0_iter6_exitcond_flatten_reg_598.read(), ap_const_lv1_0)) {
        tmp1_reg_639 = tmp1_fu_318_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_pipeline_reg_pp0_iter8_exitcond_flatten_reg_598.read(), ap_const_lv1_0)) {
        tmp_22_reg_677 = tmp_22_fu_402_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_402_p2.read())) {
        tmp_24_reg_681 = tmp_24_fu_443_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_402_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_fu_443_p2.read()))) {
        tmp_26_reg_685 = tmp_26_fu_473_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_402_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_fu_443_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_fu_473_p2.read()))) {
        tmp_28_reg_689 = tmp_28_fu_510_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_402_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_fu_443_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_fu_473_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_fu_510_p2.read()))) {
        tmp_29_reg_693 = tmp_29_fu_516_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_402_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_fu_443_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_fu_473_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_fu_510_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_fu_516_p2.read()))) {
        tmp_31_reg_697 = tmp_31_fu_546_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_402_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_fu_443_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_fu_473_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_fu_510_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_fu_516_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_fu_546_p2.read()))) {
        tmp_32_reg_701 = tmp_32_fu_565_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_fu_402_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_fu_443_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_fu_473_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_fu_510_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_fu_516_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_fu_546_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_fu_565_p2.read()))) {
        tmp_33_reg_705 = tmp_33_fu_584_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_243_p2.read(), ap_const_lv1_0))) {
        tmp_mid2_v_reg_612 = tmp_mid2_v_fu_275_p3.read();
    }
}

void normalizeHisto0::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read().range(1, 1);
}

void normalizeHisto0::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void normalizeHisto0::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read().range(2, 2);
}

void normalizeHisto0::thread_ap_condition_199() {
    ap_condition_199 = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_reg_693.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_reg_697.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_reg_701.read()));
}

void normalizeHisto0::thread_ap_condition_203() {
    ap_condition_203 = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_reg_693.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_reg_697.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_reg_701.read()));
}

void normalizeHisto0::thread_ap_condition_207() {
    ap_condition_207 = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_reg_693.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_reg_697.read()));
}

void normalizeHisto0::thread_ap_condition_211() {
    ap_condition_211 = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_reg_693.read()));
}

void normalizeHisto0::thread_ap_condition_215() {
    ap_condition_215 = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read()));
}

void normalizeHisto0::thread_ap_condition_219() {
    ap_condition_219 = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()));
}

void normalizeHisto0::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void normalizeHisto0::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void normalizeHisto0::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void normalizeHisto0::thread_average_cast7_fu_361_p1() {
    average_cast7_fu_361_p1 = esl_zext<30,27>(tmp_35_reg_650.read());
}

void normalizeHisto0::thread_average_cast8_fu_358_p1() {
    average_cast8_fu_358_p1 = esl_zext<31,27>(tmp_35_reg_650.read());
}

void normalizeHisto0::thread_average_cast_fu_364_p1() {
    average_cast_fu_364_p1 = esl_zext<28,27>(tmp_35_reg_650.read());
}

void normalizeHisto0::thread_blkIdx_phi_fu_225_p4() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_598.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        blkIdx_phi_fu_225_p4 = tmp_mid2_v_reg_612.read();
    } else {
        blkIdx_phi_fu_225_p4 = blkIdx_reg_221.read();
    }
}

void normalizeHisto0::thread_blkIdx_s_fu_269_p2() {
    blkIdx_s_fu_269_p2 = (!ap_const_lv2_1.is_01() || !blkIdx_phi_fu_225_p4.read().is_01())? sc_lv<2>(): (sc_biguint<2>(ap_const_lv2_1) + sc_biguint<2>(blkIdx_phi_fu_225_p4.read()));
}

void normalizeHisto0::thread_descriptor_V_address0() {
    descriptor_V_address0 =  (sc_lv<7>) (tmp_21_fu_353_p1.read());
}

void normalizeHisto0::thread_descriptor_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read())) {
        descriptor_V_ce0 = ap_const_logic_1;
    } else {
        descriptor_V_ce0 = ap_const_logic_0;
    }
}

void normalizeHisto0::thread_exitcond_flatten_fu_243_p2() {
    exitcond_flatten_fu_243_p2 = (!indvar_flatten_reg_210.read().is_01() || !ap_const_lv7_48.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_210.read() == ap_const_lv7_48);
}

void normalizeHisto0::thread_grp_fu_301_p0() {
    grp_fu_301_p0 =  (sc_lv<34>) (ap_const_lv65_1C71C71C8);
}

void normalizeHisto0::thread_grp_fu_301_p1() {
    grp_fu_301_p1 =  (sc_lv<32>) (grp_fu_301_p10.read());
}

void normalizeHisto0::thread_grp_fu_301_p10() {
    grp_fu_301_p10 = esl_zext<65,32>(sum_q0.read());
}

void normalizeHisto0::thread_i_2_fu_287_p2() {
    i_2_fu_287_p2 = (!i_mid2_fu_261_p3.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i_mid2_fu_261_p3.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void normalizeHisto0::thread_i_mid2_fu_261_p3() {
    i_mid2_fu_261_p3 = (!tmp_34_fu_255_p2.read()[0].is_01())? sc_lv<6>(): ((tmp_34_fu_255_p2.read()[0].to_bool())? ap_const_lv6_0: i_reg_232.read());
}

void normalizeHisto0::thread_indvar_flatten_next_fu_249_p2() {
    indvar_flatten_next_fu_249_p2 = (!indvar_flatten_reg_210.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(indvar_flatten_reg_210.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void normalizeHisto0::thread_normalized_V_addr25_gep_fu_201_p3() {
    normalized_V_addr25_gep_fu_201_p3 =  (sc_lv<7>) (ap_pipeline_reg_pp0_iter9_tmp_21_reg_660.read());
}

void normalizeHisto0::thread_normalized_V_addr_10_gep_fu_165_p3() {
    normalized_V_addr_10_gep_fu_165_p3 =  (sc_lv<7>) (ap_pipeline_reg_pp0_iter9_tmp_21_reg_660.read());
}

void normalizeHisto0::thread_normalized_V_addr_11_gep_fu_156_p3() {
    normalized_V_addr_11_gep_fu_156_p3 =  (sc_lv<7>) (ap_pipeline_reg_pp0_iter9_tmp_21_reg_660.read());
}

void normalizeHisto0::thread_normalized_V_addr_12_gep_fu_147_p3() {
    normalized_V_addr_12_gep_fu_147_p3 =  (sc_lv<7>) (ap_pipeline_reg_pp0_iter9_tmp_21_reg_660.read());
}

void normalizeHisto0::thread_normalized_V_addr_8_gep_fu_183_p3() {
    normalized_V_addr_8_gep_fu_183_p3 =  (sc_lv<7>) (ap_pipeline_reg_pp0_iter9_tmp_21_reg_660.read());
}

void normalizeHisto0::thread_normalized_V_addr_9_gep_fu_174_p3() {
    normalized_V_addr_9_gep_fu_174_p3 =  (sc_lv<7>) (ap_pipeline_reg_pp0_iter9_tmp_21_reg_660.read());
}

void normalizeHisto0::thread_normalized_V_addr_gep_fu_192_p3() {
    normalized_V_addr_gep_fu_192_p3 =  (sc_lv<7>) (ap_pipeline_reg_pp0_iter9_tmp_21_reg_660.read());
}

void normalizeHisto0::thread_normalized_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read())) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read())) {
            normalized_V_address1 = normalized_V_addr25_gep_fu_201_p3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
                    !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()))) {
            normalized_V_address1 = normalized_V_addr_gep_fu_192_p3.read();
        } else if (esl_seteq<1,1,1>(ap_condition_219.read(), ap_const_boolean_1)) {
            normalized_V_address1 = normalized_V_addr_8_gep_fu_183_p3.read();
        } else if (esl_seteq<1,1,1>(ap_condition_215.read(), ap_const_boolean_1)) {
            normalized_V_address1 = normalized_V_addr_9_gep_fu_174_p3.read();
        } else if (esl_seteq<1,1,1>(ap_condition_211.read(), ap_const_boolean_1)) {
            normalized_V_address1 = normalized_V_addr_10_gep_fu_165_p3.read();
        } else if (esl_seteq<1,1,1>(ap_condition_207.read(), ap_const_boolean_1)) {
            normalized_V_address1 = normalized_V_addr_11_gep_fu_156_p3.read();
        } else if (esl_seteq<1,1,1>(ap_condition_203.read(), ap_const_boolean_1)) {
            normalized_V_address1 = normalized_V_addr_12_gep_fu_147_p3.read();
        } else if (esl_seteq<1,1,1>(ap_condition_199.read(), ap_const_boolean_1)) {
            normalized_V_address1 =  (sc_lv<7>) (ap_pipeline_reg_pp0_iter9_tmp_21_reg_660.read());
        } else {
            normalized_V_address1 = "XXXXXXX";
        }
    } else {
        normalized_V_address1 = "XXXXXXX";
    }
}

void normalizeHisto0::thread_normalized_V_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_reg_693.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_reg_697.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_reg_701.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_reg_693.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_reg_697.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_reg_701.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_reg_693.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_reg_697.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_reg_693.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read())))) {
        normalized_V_ce1 = ap_const_logic_1;
    } else {
        normalized_V_ce1 = ap_const_logic_0;
    }
}

void normalizeHisto0::thread_normalized_V_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read())) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read())) {
            normalized_V_d1 = ap_const_lv10_199;
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
                    !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()))) {
            normalized_V_d1 = ap_const_lv10_166;
        } else if (esl_seteq<1,1,1>(ap_condition_219.read(), ap_const_boolean_1)) {
            normalized_V_d1 = ap_const_lv10_133;
        } else if (esl_seteq<1,1,1>(ap_condition_215.read(), ap_const_boolean_1)) {
            normalized_V_d1 = ap_const_lv10_100;
        } else if (esl_seteq<1,1,1>(ap_condition_211.read(), ap_const_boolean_1)) {
            normalized_V_d1 = ap_const_lv10_CC;
        } else if (esl_seteq<1,1,1>(ap_condition_207.read(), ap_const_boolean_1)) {
            normalized_V_d1 = ap_const_lv10_99;
        } else if (esl_seteq<1,1,1>(ap_condition_203.read(), ap_const_boolean_1)) {
            normalized_V_d1 = ap_const_lv10_66;
        } else if (esl_seteq<1,1,1>(ap_condition_199.read(), ap_const_boolean_1)) {
            normalized_V_d1 = storemerge_cast_cast_fu_590_p3.read();
        } else {
            normalized_V_d1 =  (sc_lv<10>) ("XXXXXXXXXX");
        }
    } else {
        normalized_V_d1 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void normalizeHisto0::thread_normalized_V_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_reg_693.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_reg_697.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_reg_701.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_reg_693.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_reg_697.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_32_reg_701.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_reg_693.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_31_reg_697.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_29_reg_693.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_28_reg_689.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_26_reg_685.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_24_reg_681.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_22_reg_677.read())))) {
        normalized_V_we1 = ap_const_logic_1;
    } else {
        normalized_V_we1 = ap_const_logic_0;
    }
}

void normalizeHisto0::thread_op2_assign_10_cast_fu_542_p1() {
    op2_assign_10_cast_fu_542_p1 = esl_zext<31,30>(tmp_41_fu_538_p1.read());
}

void normalizeHisto0::thread_op2_assign_11_cast_fu_561_p1() {
    op2_assign_11_cast_fu_561_p1 = esl_zext<27,26>(tmp_42_fu_552_p4.read());
}

void normalizeHisto0::thread_op2_assign_12_cast_fu_580_p1() {
    op2_assign_12_cast_fu_580_p1 = esl_zext<26,25>(tmp_43_fu_571_p4.read());
}

void normalizeHisto0::thread_op2_assign_7_cast_fu_439_p1() {
    op2_assign_7_cast_fu_439_p1 = esl_zext<31,30>(tmp_36_fu_435_p1.read());
}

void normalizeHisto0::thread_op2_assign_8_cast_fu_469_p1() {
    op2_assign_8_cast_fu_469_p1 = esl_zext<31,30>(tmp_38_fu_465_p1.read());
}

void normalizeHisto0::thread_op2_assign_9_cast_fu_506_p1() {
    op2_assign_9_cast_fu_506_p1 = esl_zext<29,28>(tmp_39_fu_496_p4.read());
}

void normalizeHisto0::thread_op2_assign_cast6_fu_374_p1() {
    op2_assign_cast6_fu_374_p1 = esl_zext<31,28>(op2_assign_fu_367_p3.read());
}

void normalizeHisto0::thread_op2_assign_cast_fu_378_p1() {
    op2_assign_cast_fu_378_p1 = esl_zext<29,28>(op2_assign_fu_367_p3.read());
}

void normalizeHisto0::thread_op2_assign_fu_367_p3() {
    op2_assign_fu_367_p3 = esl_concat<27,1>(tmp_35_reg_650.read(), ap_const_lv1_0);
}

void normalizeHisto0::thread_p_shl4_cast_mid2_fu_314_p1() {
    p_shl4_cast_mid2_fu_314_p1 = esl_zext<6,3>(p_shl4_cast_mid2_v_fu_307_p3.read());
}

void normalizeHisto0::thread_p_shl4_cast_mid2_v_fu_307_p3() {
    p_shl4_cast_mid2_v_fu_307_p3 = esl_concat<1,2>(ap_pipeline_reg_pp0_iter6_tmp_reg_618.read(), ap_const_lv2_0);
}

void normalizeHisto0::thread_p_shl5_cast_fu_415_p1() {
    p_shl5_cast_fu_415_p1 = esl_zext<31,30>(p_shl5_fu_408_p3.read());
}

void normalizeHisto0::thread_p_shl5_fu_408_p3() {
    p_shl5_fu_408_p3 = esl_concat<27,3>(tmp_35_reg_650.read(), ap_const_lv3_0);
}

void normalizeHisto0::thread_p_shl6_cast_fu_486_p1() {
    p_shl6_cast_fu_486_p1 = esl_zext<30,29>(p_shl6_fu_479_p3.read());
}

void normalizeHisto0::thread_p_shl6_fu_479_p3() {
    p_shl6_fu_479_p3 = esl_concat<27,2>(tmp_35_reg_650.read(), ap_const_lv2_0);
}

void normalizeHisto0::thread_p_shl_cast_mid2_fu_330_p1() {
    p_shl_cast_mid2_fu_330_p1 = esl_zext<7,6>(p_shl_cast_mid2_v_fu_323_p3.read());
}

void normalizeHisto0::thread_p_shl_cast_mid2_v_fu_323_p3() {
    p_shl_cast_mid2_v_fu_323_p3 = esl_concat<1,5>(ap_pipeline_reg_pp0_iter7_tmp_reg_618.read(), ap_const_lv5_0);
}

void normalizeHisto0::thread_storemerge_cast_cast_fu_590_p3() {
    storemerge_cast_cast_fu_590_p3 = (!tmp_33_reg_705.read()[0].is_01())? sc_lv<10>(): ((tmp_33_reg_705.read()[0].to_bool())? ap_const_lv10_33: ap_const_lv10_0);
}

void normalizeHisto0::thread_sum_address0() {
    sum_address0 =  (sc_lv<1>) (tmp_mid2_fu_293_p1.read());
}

void normalizeHisto0::thread_sum_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        sum_ce0 = ap_const_logic_1;
    } else {
        sum_ce0 = ap_const_logic_0;
    }
}

void normalizeHisto0::thread_tmp1_cast_fu_344_p1() {
    tmp1_cast_fu_344_p1 = esl_zext<7,6>(tmp1_reg_639.read());
}

void normalizeHisto0::thread_tmp1_fu_318_p2() {
    tmp1_fu_318_p2 = (!ap_pipeline_reg_pp0_iter6_i_mid2_reg_607.read().is_01() || !p_shl4_cast_mid2_fu_314_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_pipeline_reg_pp0_iter6_i_mid2_reg_607.read()) + sc_biguint<6>(p_shl4_cast_mid2_fu_314_p1.read()));
}

void normalizeHisto0::thread_tmp_20_fu_347_p2() {
    tmp_20_fu_347_p2 = (!p_shl_cast_mid2_fu_330_p1.read().is_01() || !tmp1_cast_fu_344_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(p_shl_cast_mid2_fu_330_p1.read()) + sc_biguint<7>(tmp1_cast_fu_344_p1.read()));
}

void normalizeHisto0::thread_tmp_21_fu_353_p1() {
    tmp_21_fu_353_p1 = esl_zext<64,7>(tmp_20_fu_347_p2.read());
}

void normalizeHisto0::thread_tmp_22_cast2_fu_394_p1() {
    tmp_22_cast2_fu_394_p1 = esl_sext<31,15>(descriptor_V_q0.read());
}

void normalizeHisto0::thread_tmp_22_cast3_fu_390_p1() {
    tmp_22_cast3_fu_390_p1 = esl_sext<28,15>(descriptor_V_q0.read());
}

void normalizeHisto0::thread_tmp_22_cast4_fu_386_p1() {
    tmp_22_cast4_fu_386_p1 = esl_sext<27,15>(descriptor_V_q0.read());
}

void normalizeHisto0::thread_tmp_22_cast5_fu_382_p1() {
    tmp_22_cast5_fu_382_p1 = esl_sext<26,15>(descriptor_V_q0.read());
}

void normalizeHisto0::thread_tmp_22_cast_fu_398_p1() {
    tmp_22_cast_fu_398_p1 = esl_sext<29,15>(descriptor_V_q0.read());
}

void normalizeHisto0::thread_tmp_22_fu_402_p2() {
    tmp_22_fu_402_p2 = (!tmp_22_cast_fu_398_p1.read().is_01() || !op2_assign_cast_fu_378_p1.read().is_01())? sc_lv<1>(): (sc_bigint<29>(tmp_22_cast_fu_398_p1.read()) > sc_bigint<29>(op2_assign_cast_fu_378_p1.read()));
}

void normalizeHisto0::thread_tmp_23_fu_419_p2() {
    tmp_23_fu_419_p2 = (!p_shl5_cast_fu_415_p1.read().is_01() || !average_cast8_fu_358_p1.read().is_01())? sc_lv<31>(): (sc_biguint<31>(p_shl5_cast_fu_415_p1.read()) - sc_biguint<31>(average_cast8_fu_358_p1.read()));
}

void normalizeHisto0::thread_tmp_24_fu_443_p2() {
    tmp_24_fu_443_p2 = (!tmp_22_cast2_fu_394_p1.read().is_01() || !op2_assign_7_cast_fu_439_p1.read().is_01())? sc_lv<1>(): (sc_bigint<31>(tmp_22_cast2_fu_394_p1.read()) > sc_bigint<31>(op2_assign_7_cast_fu_439_p1.read()));
}

void normalizeHisto0::thread_tmp_25_fu_449_p2() {
    tmp_25_fu_449_p2 = (!p_shl5_cast_fu_415_p1.read().is_01() || !op2_assign_cast6_fu_374_p1.read().is_01())? sc_lv<31>(): (sc_biguint<31>(p_shl5_cast_fu_415_p1.read()) - sc_biguint<31>(op2_assign_cast6_fu_374_p1.read()));
}

void normalizeHisto0::thread_tmp_26_fu_473_p2() {
    tmp_26_fu_473_p2 = (!tmp_22_cast2_fu_394_p1.read().is_01() || !op2_assign_8_cast_fu_469_p1.read().is_01())? sc_lv<1>(): (sc_bigint<31>(tmp_22_cast2_fu_394_p1.read()) > sc_bigint<31>(op2_assign_8_cast_fu_469_p1.read()));
}

void normalizeHisto0::thread_tmp_27_fu_490_p2() {
    tmp_27_fu_490_p2 = (!p_shl6_cast_fu_486_p1.read().is_01() || !average_cast7_fu_361_p1.read().is_01())? sc_lv<30>(): (sc_biguint<30>(p_shl6_cast_fu_486_p1.read()) + sc_biguint<30>(average_cast7_fu_361_p1.read()));
}

void normalizeHisto0::thread_tmp_28_fu_510_p2() {
    tmp_28_fu_510_p2 = (!tmp_22_cast_fu_398_p1.read().is_01() || !op2_assign_9_cast_fu_506_p1.read().is_01())? sc_lv<1>(): (sc_bigint<29>(tmp_22_cast_fu_398_p1.read()) > sc_bigint<29>(op2_assign_9_cast_fu_506_p1.read()));
}

void normalizeHisto0::thread_tmp_29_fu_516_p2() {
    tmp_29_fu_516_p2 = (!tmp_22_cast3_fu_390_p1.read().is_01() || !average_cast_fu_364_p1.read().is_01())? sc_lv<1>(): (sc_bigint<28>(tmp_22_cast3_fu_390_p1.read()) > sc_bigint<28>(average_cast_fu_364_p1.read()));
}

void normalizeHisto0::thread_tmp_30_fu_522_p2() {
    tmp_30_fu_522_p2 = (!p_shl6_cast_fu_486_p1.read().is_01() || !average_cast7_fu_361_p1.read().is_01())? sc_lv<30>(): (sc_biguint<30>(p_shl6_cast_fu_486_p1.read()) - sc_biguint<30>(average_cast7_fu_361_p1.read()));
}

void normalizeHisto0::thread_tmp_31_fu_546_p2() {
    tmp_31_fu_546_p2 = (!tmp_22_cast2_fu_394_p1.read().is_01() || !op2_assign_10_cast_fu_542_p1.read().is_01())? sc_lv<1>(): (sc_bigint<31>(tmp_22_cast2_fu_394_p1.read()) > sc_bigint<31>(op2_assign_10_cast_fu_542_p1.read()));
}

void normalizeHisto0::thread_tmp_32_fu_565_p2() {
    tmp_32_fu_565_p2 = (!tmp_22_cast4_fu_386_p1.read().is_01() || !op2_assign_11_cast_fu_561_p1.read().is_01())? sc_lv<1>(): (sc_bigint<27>(tmp_22_cast4_fu_386_p1.read()) > sc_bigint<27>(op2_assign_11_cast_fu_561_p1.read()));
}

void normalizeHisto0::thread_tmp_33_fu_584_p2() {
    tmp_33_fu_584_p2 = (!tmp_22_cast5_fu_382_p1.read().is_01() || !op2_assign_12_cast_fu_580_p1.read().is_01())? sc_lv<1>(): (sc_bigint<26>(tmp_22_cast5_fu_382_p1.read()) > sc_bigint<26>(op2_assign_12_cast_fu_580_p1.read()));
}

void normalizeHisto0::thread_tmp_34_fu_255_p2() {
    tmp_34_fu_255_p2 = (!i_reg_232.read().is_01() || !ap_const_lv6_24.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_232.read() == ap_const_lv6_24);
}

void normalizeHisto0::thread_tmp_36_fu_435_p1() {
    tmp_36_fu_435_p1 = esl_sext<30,29>(tmp_s_fu_425_p4.read());
}

void normalizeHisto0::thread_tmp_37_fu_455_p4() {
    tmp_37_fu_455_p4 = tmp_25_fu_449_p2.read().range(30, 2);
}

void normalizeHisto0::thread_tmp_38_fu_465_p1() {
    tmp_38_fu_465_p1 = esl_sext<30,29>(tmp_37_fu_455_p4.read());
}

void normalizeHisto0::thread_tmp_39_fu_496_p4() {
    tmp_39_fu_496_p4 = tmp_27_fu_490_p2.read().range(29, 2);
}

void normalizeHisto0::thread_tmp_40_fu_528_p4() {
    tmp_40_fu_528_p4 = tmp_30_fu_522_p2.read().range(29, 2);
}

void normalizeHisto0::thread_tmp_41_fu_538_p1() {
    tmp_41_fu_538_p1 = esl_sext<30,28>(tmp_40_fu_528_p4.read());
}

void normalizeHisto0::thread_tmp_42_fu_552_p4() {
    tmp_42_fu_552_p4 = mul_reg_644.read().range(64, 39);
}

void normalizeHisto0::thread_tmp_43_fu_571_p4() {
    tmp_43_fu_571_p4 = mul_reg_644.read().range(64, 40);
}

void normalizeHisto0::thread_tmp_fu_283_p1() {
    tmp_fu_283_p1 = tmp_mid2_v_fu_275_p3.read().range(1-1, 0);
}

void normalizeHisto0::thread_tmp_mid2_fu_293_p1() {
    tmp_mid2_fu_293_p1 = esl_zext<64,2>(tmp_mid2_v_reg_612.read());
}

void normalizeHisto0::thread_tmp_mid2_v_fu_275_p3() {
    tmp_mid2_v_fu_275_p3 = (!tmp_34_fu_255_p2.read()[0].is_01())? sc_lv<2>(): ((tmp_34_fu_255_p2.read()[0].to_bool())? blkIdx_s_fu_269_p2.read(): blkIdx_phi_fu_225_p4.read());
}

void normalizeHisto0::thread_tmp_s_fu_425_p4() {
    tmp_s_fu_425_p4 = tmp_23_fu_419_p2.read().range(30, 2);
}

void normalizeHisto0::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter10.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter9.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && !esl_seteq<1,1,1>(exitcond_flatten_fu_243_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && !esl_seteq<1,1,1>(exitcond_flatten_fu_243_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<3>) ("XXX");
            break;
    }
}

}

