// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XHOG_H
#define XHOG_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xhog_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Specs_BaseAddress;
    u32 Control_bus_BaseAddress;
} XHog_Config;
#endif

typedef struct {
    u32 Specs_BaseAddress;
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XHog;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XHog_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XHog_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XHog_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XHog_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XHog_Initialize(XHog *InstancePtr, u16 DeviceId);
XHog_Config* XHog_LookupConfig(u16 DeviceId);
int XHog_CfgInitialize(XHog *InstancePtr, XHog_Config *ConfigPtr);
#else
int XHog_Initialize(XHog *InstancePtr, const char* InstanceName);
int XHog_Release(XHog *InstancePtr);
#endif

void XHog_Start(XHog *InstancePtr);
u32 XHog_IsDone(XHog *InstancePtr);
u32 XHog_IsIdle(XHog *InstancePtr);
u32 XHog_IsReady(XHog *InstancePtr);
void XHog_EnableAutoRestart(XHog *InstancePtr);
void XHog_DisableAutoRestart(XHog *InstancePtr);

void XHog_Set_image0(XHog *InstancePtr, u32 Data);
u32 XHog_Get_image0(XHog *InstancePtr);
u32 XHog_Get_specs_BaseAddress(XHog *InstancePtr);
u32 XHog_Get_specs_HighAddress(XHog *InstancePtr);
u32 XHog_Get_specs_TotalBytes(XHog *InstancePtr);
u32 XHog_Get_specs_BitWidth(XHog *InstancePtr);
u32 XHog_Get_specs_Depth(XHog *InstancePtr);
u32 XHog_Write_specs_Words(XHog *InstancePtr, int offset, int *data, int length);
u32 XHog_Read_specs_Words(XHog *InstancePtr, int offset, int *data, int length);
u32 XHog_Write_specs_Bytes(XHog *InstancePtr, int offset, char *data, int length);
u32 XHog_Read_specs_Bytes(XHog *InstancePtr, int offset, char *data, int length);

void XHog_InterruptGlobalEnable(XHog *InstancePtr);
void XHog_InterruptGlobalDisable(XHog *InstancePtr);
void XHog_InterruptEnable(XHog *InstancePtr, u32 Mask);
void XHog_InterruptDisable(XHog *InstancePtr, u32 Mask);
void XHog_InterruptClear(XHog *InstancePtr, u32 Mask);
u32 XHog_InterruptGetEnabled(XHog *InstancePtr);
u32 XHog_InterruptGetStatus(XHog *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
