// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module normalizeHisto1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sum_address0,
        sum_ce0,
        sum_q0,
        descriptor_V_address0,
        descriptor_V_ce0,
        descriptor_V_q0,
        normalized_V_address1,
        normalized_V_ce1,
        normalized_V_we1,
        normalized_V_d1
);

parameter    ap_ST_fsm_state1 = 3'b1;
parameter    ap_ST_fsm_pp0_stage0 = 3'b10;
parameter    ap_ST_fsm_state13 = 3'b100;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv10_66 = 10'b1100110;
parameter    ap_const_lv10_99 = 10'b10011001;
parameter    ap_const_lv10_CC = 10'b11001100;
parameter    ap_const_lv10_100 = 10'b100000000;
parameter    ap_const_lv10_133 = 10'b100110011;
parameter    ap_const_lv10_166 = 10'b101100110;
parameter    ap_const_lv10_199 = 10'b110011001;
parameter    ap_const_lv7_48 = 7'b1001000;
parameter    ap_const_lv7_1 = 7'b1;
parameter    ap_const_lv6_24 = 6'b100100;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv65_1C71C71C8 = 65'b111000111000111000111000111001000;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv32_26 = 32'b100110;
parameter    ap_const_lv32_40 = 32'b1000000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv32_1D = 32'b11101;
parameter    ap_const_lv32_27 = 32'b100111;
parameter    ap_const_lv32_28 = 32'b101000;
parameter    ap_const_lv10_33 = 10'b110011;
parameter    ap_const_lv10_0 = 10'b0000000000;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] sum_address0;
output   sum_ce0;
input  [31:0] sum_q0;
output  [6:0] descriptor_V_address0;
output   descriptor_V_ce0;
input  [14:0] descriptor_V_q0;
output  [6:0] normalized_V_address1;
output   normalized_V_ce1;
output   normalized_V_we1;
output  [9:0] normalized_V_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg sum_ce0;
reg descriptor_V_ce0;
reg[6:0] normalized_V_address1;
reg normalized_V_ce1;
reg normalized_V_we1;
reg[9:0] normalized_V_d1;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state1;
reg   [6:0] indvar_flatten_reg_210;
reg   [1:0] blkIdx_reg_221;
reg   [5:0] i_reg_232;
wire   [0:0] exitcond_flatten_fu_243_p2;
reg   [0:0] exitcond_flatten_reg_598;
wire   [0:0] ap_CS_fsm_pp0_stage0;
reg   [0:0] ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_598;
reg   [0:0] ap_pipeline_reg_pp0_iter2_exitcond_flatten_reg_598;
reg   [0:0] ap_pipeline_reg_pp0_iter3_exitcond_flatten_reg_598;
reg   [0:0] ap_pipeline_reg_pp0_iter4_exitcond_flatten_reg_598;
reg   [0:0] ap_pipeline_reg_pp0_iter5_exitcond_flatten_reg_598;
reg   [0:0] ap_pipeline_reg_pp0_iter6_exitcond_flatten_reg_598;
reg   [0:0] ap_pipeline_reg_pp0_iter7_exitcond_flatten_reg_598;
reg   [0:0] ap_pipeline_reg_pp0_iter8_exitcond_flatten_reg_598;
wire   [6:0] indvar_flatten_next_fu_249_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [5:0] i_mid2_fu_261_p3;
reg   [5:0] i_mid2_reg_607;
reg   [5:0] ap_pipeline_reg_pp0_iter1_i_mid2_reg_607;
reg   [5:0] ap_pipeline_reg_pp0_iter2_i_mid2_reg_607;
reg   [5:0] ap_pipeline_reg_pp0_iter3_i_mid2_reg_607;
reg   [5:0] ap_pipeline_reg_pp0_iter4_i_mid2_reg_607;
reg   [5:0] ap_pipeline_reg_pp0_iter5_i_mid2_reg_607;
reg   [5:0] ap_pipeline_reg_pp0_iter6_i_mid2_reg_607;
wire   [1:0] tmp_mid2_v_fu_275_p3;
reg   [1:0] tmp_mid2_v_reg_612;
wire   [0:0] tmp_fu_283_p1;
reg   [0:0] tmp_reg_618;
reg   [0:0] ap_pipeline_reg_pp0_iter1_tmp_reg_618;
reg   [0:0] ap_pipeline_reg_pp0_iter2_tmp_reg_618;
reg   [0:0] ap_pipeline_reg_pp0_iter3_tmp_reg_618;
reg   [0:0] ap_pipeline_reg_pp0_iter4_tmp_reg_618;
reg   [0:0] ap_pipeline_reg_pp0_iter5_tmp_reg_618;
reg   [0:0] ap_pipeline_reg_pp0_iter6_tmp_reg_618;
reg   [0:0] ap_pipeline_reg_pp0_iter7_tmp_reg_618;
wire   [5:0] i_1_fu_287_p2;
wire   [5:0] tmp1_fu_318_p2;
reg   [5:0] tmp1_reg_639;
wire   [64:0] grp_fu_301_p2;
reg   [64:0] mul_reg_644;
reg   [26:0] tmp_5_reg_650;
wire   [63:0] tmp_4_fu_353_p1;
reg   [63:0] tmp_4_reg_660;
reg   [63:0] ap_pipeline_reg_pp0_iter9_tmp_4_reg_660;
wire   [0:0] tmp_6_fu_402_p2;
reg   [0:0] tmp_6_reg_677;
wire   [0:0] tmp_8_fu_443_p2;
reg   [0:0] tmp_8_reg_681;
wire   [0:0] tmp_10_fu_473_p2;
reg   [0:0] tmp_10_reg_685;
wire   [0:0] tmp_12_fu_510_p2;
reg   [0:0] tmp_12_reg_689;
wire   [0:0] tmp_13_fu_516_p2;
reg   [0:0] tmp_13_reg_693;
wire   [0:0] tmp_15_fu_546_p2;
reg   [0:0] tmp_15_reg_697;
wire   [0:0] tmp_16_fu_565_p2;
reg   [0:0] tmp_16_reg_701;
wire   [0:0] tmp_17_fu_584_p2;
reg   [0:0] tmp_17_reg_705;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg   [1:0] blkIdx_phi_fu_225_p4;
wire   [63:0] tmp_mid2_fu_293_p1;
wire   [6:0] normalized_V_addr_6_gep_fu_147_p3;
wire   [6:0] normalized_V_addr_5_gep_fu_156_p3;
wire   [6:0] normalized_V_addr_4_gep_fu_165_p3;
wire   [6:0] normalized_V_addr_3_gep_fu_174_p3;
wire   [6:0] normalized_V_addr_2_gep_fu_183_p3;
wire   [6:0] normalized_V_addr_1_gep_fu_192_p3;
wire   [6:0] normalized_V_addr_gep_fu_201_p3;
wire   [9:0] storemerge_cast_cast_fu_590_p3;
wire   [0:0] tmp_2_fu_255_p2;
wire   [1:0] blkIdx_s_fu_269_p2;
wire   [33:0] grp_fu_301_p0;
wire   [31:0] grp_fu_301_p1;
wire   [2:0] p_shl1_cast_mid2_v_fu_307_p3;
wire   [5:0] p_shl1_cast_mid2_fu_314_p1;
wire   [5:0] p_shl_cast_mid2_v_fu_323_p3;
wire   [6:0] p_shl_cast_mid2_fu_330_p1;
wire   [6:0] tmp1_cast_fu_344_p1;
wire   [6:0] tmp_3_fu_347_p2;
wire   [27:0] op2_assign_fu_367_p3;
wire  signed [28:0] tmp_5_cast_fu_398_p1;
wire   [28:0] op2_assign_cast_fu_378_p1;
wire   [29:0] p_shl2_fu_408_p3;
wire   [30:0] p_shl2_cast_fu_415_p1;
wire   [30:0] average_cast8_fu_358_p1;
wire   [30:0] tmp_7_fu_419_p2;
wire   [28:0] tmp_s_fu_425_p4;
wire  signed [29:0] tmp_18_fu_435_p1;
wire  signed [30:0] tmp_5_cast2_fu_394_p1;
wire   [30:0] op2_assign_1_cast_fu_439_p1;
wire   [30:0] op2_assign_cast6_fu_374_p1;
wire   [30:0] tmp_9_fu_449_p2;
wire   [28:0] tmp_19_fu_455_p4;
wire  signed [29:0] tmp_20_fu_465_p1;
wire   [30:0] op2_assign_2_cast_fu_469_p1;
wire   [28:0] p_shl3_fu_479_p3;
wire   [29:0] p_shl3_cast_fu_486_p1;
wire   [29:0] average_cast7_fu_361_p1;
wire   [29:0] tmp_11_fu_490_p2;
wire   [27:0] tmp_21_fu_496_p4;
wire   [28:0] op2_assign_3_cast_fu_506_p1;
wire  signed [27:0] tmp_5_cast3_fu_390_p1;
wire   [27:0] average_cast_fu_364_p1;
wire   [29:0] tmp_14_fu_522_p2;
wire   [27:0] tmp_22_fu_528_p4;
wire  signed [29:0] tmp_23_fu_538_p1;
wire   [30:0] op2_assign_4_cast_fu_542_p1;
wire   [25:0] tmp_24_fu_552_p4;
wire  signed [26:0] tmp_5_cast4_fu_386_p1;
wire   [26:0] op2_assign_5_cast_fu_561_p1;
wire   [24:0] tmp_25_fu_571_p4;
wire  signed [25:0] tmp_5_cast5_fu_382_p1;
wire   [25:0] op2_assign_6_cast_fu_580_p1;
wire   [0:0] ap_CS_fsm_state13;
reg   [2:0] ap_NS_fsm;
wire   [64:0] grp_fu_301_p10;
reg    ap_condition_199;
reg    ap_condition_203;
reg    ap_condition_207;
reg    ap_condition_211;
reg    ap_condition_215;
reg    ap_condition_219;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'b1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
end

hog_mul_34ns_32nsjbC #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 34 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 65 ))
hog_mul_34ns_32nsjbC_x_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_301_p0),
    .din1(grp_fu_301_p1),
    .ce(1'b1),
    .dout(grp_fu_301_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & ~(exitcond_flatten_fu_243_p2 == 1'b0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_fu_243_p2 == 1'b0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end else if ((((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & ~(exitcond_flatten_fu_243_p2 == 1'b0)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_598 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        blkIdx_reg_221 <= tmp_mid2_v_reg_612;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        blkIdx_reg_221 <= ap_const_lv2_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_fu_243_p2 == 1'b0))) begin
        i_reg_232 <= i_1_fu_287_p2;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        i_reg_232 <= ap_const_lv6_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_fu_243_p2 == 1'b0))) begin
        indvar_flatten_reg_210 <= indvar_flatten_next_fu_249_p2;
    end else if (((ap_CS_fsm_state1 == 1'b1) & ~(ap_start == 1'b0))) begin
        indvar_flatten_reg_210 <= ap_const_lv7_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_598 <= exitcond_flatten_reg_598;
        ap_pipeline_reg_pp0_iter1_i_mid2_reg_607 <= i_mid2_reg_607;
        ap_pipeline_reg_pp0_iter1_tmp_reg_618 <= tmp_reg_618;
        exitcond_flatten_reg_598 <= exitcond_flatten_fu_243_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == 1'b1)) begin
        ap_pipeline_reg_pp0_iter2_exitcond_flatten_reg_598 <= ap_pipeline_reg_pp0_iter1_exitcond_flatten_reg_598;
        ap_pipeline_reg_pp0_iter2_i_mid2_reg_607 <= ap_pipeline_reg_pp0_iter1_i_mid2_reg_607;
        ap_pipeline_reg_pp0_iter2_tmp_reg_618 <= ap_pipeline_reg_pp0_iter1_tmp_reg_618;
        ap_pipeline_reg_pp0_iter3_exitcond_flatten_reg_598 <= ap_pipeline_reg_pp0_iter2_exitcond_flatten_reg_598;
        ap_pipeline_reg_pp0_iter3_i_mid2_reg_607 <= ap_pipeline_reg_pp0_iter2_i_mid2_reg_607;
        ap_pipeline_reg_pp0_iter3_tmp_reg_618 <= ap_pipeline_reg_pp0_iter2_tmp_reg_618;
        ap_pipeline_reg_pp0_iter4_exitcond_flatten_reg_598 <= ap_pipeline_reg_pp0_iter3_exitcond_flatten_reg_598;
        ap_pipeline_reg_pp0_iter4_i_mid2_reg_607 <= ap_pipeline_reg_pp0_iter3_i_mid2_reg_607;
        ap_pipeline_reg_pp0_iter4_tmp_reg_618 <= ap_pipeline_reg_pp0_iter3_tmp_reg_618;
        ap_pipeline_reg_pp0_iter5_exitcond_flatten_reg_598 <= ap_pipeline_reg_pp0_iter4_exitcond_flatten_reg_598;
        ap_pipeline_reg_pp0_iter5_i_mid2_reg_607 <= ap_pipeline_reg_pp0_iter4_i_mid2_reg_607;
        ap_pipeline_reg_pp0_iter5_tmp_reg_618 <= ap_pipeline_reg_pp0_iter4_tmp_reg_618;
        ap_pipeline_reg_pp0_iter6_exitcond_flatten_reg_598 <= ap_pipeline_reg_pp0_iter5_exitcond_flatten_reg_598;
        ap_pipeline_reg_pp0_iter6_i_mid2_reg_607 <= ap_pipeline_reg_pp0_iter5_i_mid2_reg_607;
        ap_pipeline_reg_pp0_iter6_tmp_reg_618 <= ap_pipeline_reg_pp0_iter5_tmp_reg_618;
        ap_pipeline_reg_pp0_iter7_exitcond_flatten_reg_598 <= ap_pipeline_reg_pp0_iter6_exitcond_flatten_reg_598;
        ap_pipeline_reg_pp0_iter7_tmp_reg_618 <= ap_pipeline_reg_pp0_iter6_tmp_reg_618;
        ap_pipeline_reg_pp0_iter8_exitcond_flatten_reg_598 <= ap_pipeline_reg_pp0_iter7_exitcond_flatten_reg_598;
        ap_pipeline_reg_pp0_iter9_tmp_4_reg_660[6 : 0] <= tmp_4_reg_660[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_fu_243_p2 == 1'b0))) begin
        i_mid2_reg_607 <= i_mid2_fu_261_p3;
        tmp_reg_618 <= tmp_fu_283_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_pipeline_reg_pp0_iter7_exitcond_flatten_reg_598 == 1'b0)) begin
        mul_reg_644 <= grp_fu_301_p2;
        tmp_4_reg_660[6 : 0] <= tmp_4_fu_353_p1[6 : 0];
        tmp_5_reg_650 <= {{grp_fu_301_p2[ap_const_lv32_40 : ap_const_lv32_26]}};
    end
end

always @ (posedge ap_clk) begin
    if ((ap_pipeline_reg_pp0_iter6_exitcond_flatten_reg_598 == 1'b0)) begin
        tmp1_reg_639 <= tmp1_fu_318_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == tmp_6_fu_402_p2) & (1'b0 == tmp_8_fu_443_p2))) begin
        tmp_10_reg_685 <= tmp_10_fu_473_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == tmp_6_fu_402_p2) & (1'b0 == tmp_8_fu_443_p2) & (1'b0 == tmp_10_fu_473_p2))) begin
        tmp_12_reg_689 <= tmp_12_fu_510_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == tmp_6_fu_402_p2) & (1'b0 == tmp_8_fu_443_p2) & (1'b0 == tmp_10_fu_473_p2) & (1'b0 == tmp_12_fu_510_p2))) begin
        tmp_13_reg_693 <= tmp_13_fu_516_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == tmp_6_fu_402_p2) & (1'b0 == tmp_8_fu_443_p2) & (1'b0 == tmp_10_fu_473_p2) & (1'b0 == tmp_12_fu_510_p2) & (1'b0 == tmp_13_fu_516_p2))) begin
        tmp_15_reg_697 <= tmp_15_fu_546_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == tmp_6_fu_402_p2) & (1'b0 == tmp_8_fu_443_p2) & (1'b0 == tmp_10_fu_473_p2) & (1'b0 == tmp_12_fu_510_p2) & (1'b0 == tmp_13_fu_516_p2) & (1'b0 == tmp_15_fu_546_p2))) begin
        tmp_16_reg_701 <= tmp_16_fu_565_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == tmp_6_fu_402_p2) & (1'b0 == tmp_8_fu_443_p2) & (1'b0 == tmp_10_fu_473_p2) & (1'b0 == tmp_12_fu_510_p2) & (1'b0 == tmp_13_fu_516_p2) & (1'b0 == tmp_15_fu_546_p2) & (1'b0 == tmp_16_fu_565_p2))) begin
        tmp_17_reg_705 <= tmp_17_fu_584_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_pipeline_reg_pp0_iter8_exitcond_flatten_reg_598 == 1'b0)) begin
        tmp_6_reg_677 <= tmp_6_fu_402_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == tmp_6_fu_402_p2)) begin
        tmp_8_reg_681 <= tmp_8_fu_443_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_fu_243_p2 == 1'b0))) begin
        tmp_mid2_v_reg_612 <= tmp_mid2_v_fu_275_p3;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1)) | (1'b1 == ap_CS_fsm_state13))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (ap_CS_fsm_state1 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_598 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        blkIdx_phi_fu_225_p4 = tmp_mid2_v_reg_612;
    end else begin
        blkIdx_phi_fu_225_p4 = blkIdx_reg_221;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter8)) begin
        descriptor_V_ce0 = 1'b1;
    end else begin
        descriptor_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter10)) begin
        if (~(1'b0 == tmp_6_reg_677)) begin
            normalized_V_address1 = normalized_V_addr_gep_fu_201_p3;
        end else if (((1'b0 == tmp_6_reg_677) & ~(1'b0 == tmp_8_reg_681))) begin
            normalized_V_address1 = normalized_V_addr_1_gep_fu_192_p3;
        end else if ((ap_condition_219 == 1'b1)) begin
            normalized_V_address1 = normalized_V_addr_2_gep_fu_183_p3;
        end else if ((ap_condition_215 == 1'b1)) begin
            normalized_V_address1 = normalized_V_addr_3_gep_fu_174_p3;
        end else if ((ap_condition_211 == 1'b1)) begin
            normalized_V_address1 = normalized_V_addr_4_gep_fu_165_p3;
        end else if ((ap_condition_207 == 1'b1)) begin
            normalized_V_address1 = normalized_V_addr_5_gep_fu_156_p3;
        end else if ((ap_condition_203 == 1'b1)) begin
            normalized_V_address1 = normalized_V_addr_6_gep_fu_147_p3;
        end else if ((ap_condition_199 == 1'b1)) begin
            normalized_V_address1 = ap_pipeline_reg_pp0_iter9_tmp_4_reg_660;
        end else begin
            normalized_V_address1 = 'bx;
        end
    end else begin
        normalized_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter10) & (1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & (1'b0 == tmp_12_reg_689) & (1'b0 == tmp_13_reg_693) & (1'b0 == tmp_15_reg_697) & (1'b0 == tmp_16_reg_701)) | ((1'b1 == ap_enable_reg_pp0_iter10) & (1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & (1'b0 == tmp_12_reg_689) & (1'b0 == tmp_13_reg_693) & (1'b0 == tmp_15_reg_697) & ~(1'b0 == tmp_16_reg_701)) | ((1'b1 == ap_enable_reg_pp0_iter10) & (1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & (1'b0 == tmp_12_reg_689) & (1'b0 == tmp_13_reg_693) & ~(1'b0 == tmp_15_reg_697)) | ((1'b1 == ap_enable_reg_pp0_iter10) & (1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & (1'b0 == tmp_12_reg_689) & ~(1'b0 == tmp_13_reg_693)) | ((1'b1 == ap_enable_reg_pp0_iter10) & (1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & ~(1'b0 == tmp_12_reg_689)) | ((1'b1 == ap_enable_reg_pp0_iter10) & (1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & ~(1'b0 == tmp_10_reg_685)) | ((1'b1 == ap_enable_reg_pp0_iter10) & (1'b0 == tmp_6_reg_677) & ~(1'b0 == tmp_8_reg_681)) | ((1'b1 == ap_enable_reg_pp0_iter10) & ~(1'b0 == tmp_6_reg_677)))) begin
        normalized_V_ce1 = 1'b1;
    end else begin
        normalized_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_enable_reg_pp0_iter10)) begin
        if (~(1'b0 == tmp_6_reg_677)) begin
            normalized_V_d1 = ap_const_lv10_199;
        end else if (((1'b0 == tmp_6_reg_677) & ~(1'b0 == tmp_8_reg_681))) begin
            normalized_V_d1 = ap_const_lv10_166;
        end else if ((ap_condition_219 == 1'b1)) begin
            normalized_V_d1 = ap_const_lv10_133;
        end else if ((ap_condition_215 == 1'b1)) begin
            normalized_V_d1 = ap_const_lv10_100;
        end else if ((ap_condition_211 == 1'b1)) begin
            normalized_V_d1 = ap_const_lv10_CC;
        end else if ((ap_condition_207 == 1'b1)) begin
            normalized_V_d1 = ap_const_lv10_99;
        end else if ((ap_condition_203 == 1'b1)) begin
            normalized_V_d1 = ap_const_lv10_66;
        end else if ((ap_condition_199 == 1'b1)) begin
            normalized_V_d1 = storemerge_cast_cast_fu_590_p3;
        end else begin
            normalized_V_d1 = 'bx;
        end
    end else begin
        normalized_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_enable_reg_pp0_iter10) & (1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & (1'b0 == tmp_12_reg_689) & (1'b0 == tmp_13_reg_693) & (1'b0 == tmp_15_reg_697) & (1'b0 == tmp_16_reg_701)) | ((1'b1 == ap_enable_reg_pp0_iter10) & (1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & (1'b0 == tmp_12_reg_689) & (1'b0 == tmp_13_reg_693) & (1'b0 == tmp_15_reg_697) & ~(1'b0 == tmp_16_reg_701)) | ((1'b1 == ap_enable_reg_pp0_iter10) & (1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & (1'b0 == tmp_12_reg_689) & (1'b0 == tmp_13_reg_693) & ~(1'b0 == tmp_15_reg_697)) | ((1'b1 == ap_enable_reg_pp0_iter10) & (1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & (1'b0 == tmp_12_reg_689) & ~(1'b0 == tmp_13_reg_693)) | ((1'b1 == ap_enable_reg_pp0_iter10) & (1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & ~(1'b0 == tmp_12_reg_689)) | ((1'b1 == ap_enable_reg_pp0_iter10) & (1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & ~(1'b0 == tmp_10_reg_685)) | ((1'b1 == ap_enable_reg_pp0_iter10) & (1'b0 == tmp_6_reg_677) & ~(1'b0 == tmp_8_reg_681)) | ((1'b1 == ap_enable_reg_pp0_iter10) & ~(1'b0 == tmp_6_reg_677)))) begin
        normalized_V_we1 = 1'b1;
    end else begin
        normalized_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        sum_ce0 = 1'b1;
    end else begin
        sum_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter10) & ~(1'b1 == ap_enable_reg_pp0_iter9)) & ~((1'b1 == ap_enable_reg_pp0_iter0) & ~(exitcond_flatten_fu_243_p2 == 1'b0) & ~(1'b1 == ap_enable_reg_pp0_iter1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b1 == ap_enable_reg_pp0_iter0) & ~(exitcond_flatten_fu_243_p2 == 1'b0) & ~(1'b1 == ap_enable_reg_pp0_iter1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[ap_const_lv32_1];

assign ap_CS_fsm_state1 = ap_CS_fsm[ap_const_lv32_0];

assign ap_CS_fsm_state13 = ap_CS_fsm[ap_const_lv32_2];

always @ (*) begin
    ap_condition_199 = ((1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & (1'b0 == tmp_12_reg_689) & (1'b0 == tmp_13_reg_693) & (1'b0 == tmp_15_reg_697) & (1'b0 == tmp_16_reg_701));
end

always @ (*) begin
    ap_condition_203 = ((1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & (1'b0 == tmp_12_reg_689) & (1'b0 == tmp_13_reg_693) & (1'b0 == tmp_15_reg_697) & ~(1'b0 == tmp_16_reg_701));
end

always @ (*) begin
    ap_condition_207 = ((1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & (1'b0 == tmp_12_reg_689) & (1'b0 == tmp_13_reg_693) & ~(1'b0 == tmp_15_reg_697));
end

always @ (*) begin
    ap_condition_211 = ((1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & (1'b0 == tmp_12_reg_689) & ~(1'b0 == tmp_13_reg_693));
end

always @ (*) begin
    ap_condition_215 = ((1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & (1'b0 == tmp_10_reg_685) & ~(1'b0 == tmp_12_reg_689));
end

always @ (*) begin
    ap_condition_219 = ((1'b0 == tmp_6_reg_677) & (1'b0 == tmp_8_reg_681) & ~(1'b0 == tmp_10_reg_685));
end

assign average_cast7_fu_361_p1 = tmp_5_reg_650;

assign average_cast8_fu_358_p1 = tmp_5_reg_650;

assign average_cast_fu_364_p1 = tmp_5_reg_650;

assign blkIdx_s_fu_269_p2 = (ap_const_lv2_1 + blkIdx_phi_fu_225_p4);

assign descriptor_V_address0 = tmp_4_fu_353_p1;

assign exitcond_flatten_fu_243_p2 = ((indvar_flatten_reg_210 == ap_const_lv7_48) ? 1'b1 : 1'b0);

assign grp_fu_301_p0 = ap_const_lv65_1C71C71C8;

assign grp_fu_301_p1 = grp_fu_301_p10;

assign grp_fu_301_p10 = sum_q0;

assign i_1_fu_287_p2 = (i_mid2_fu_261_p3 + ap_const_lv6_1);

assign i_mid2_fu_261_p3 = ((tmp_2_fu_255_p2[0:0] === 1'b1) ? ap_const_lv6_0 : i_reg_232);

assign indvar_flatten_next_fu_249_p2 = (indvar_flatten_reg_210 + ap_const_lv7_1);

assign normalized_V_addr_1_gep_fu_192_p3 = ap_pipeline_reg_pp0_iter9_tmp_4_reg_660;

assign normalized_V_addr_2_gep_fu_183_p3 = ap_pipeline_reg_pp0_iter9_tmp_4_reg_660;

assign normalized_V_addr_3_gep_fu_174_p3 = ap_pipeline_reg_pp0_iter9_tmp_4_reg_660;

assign normalized_V_addr_4_gep_fu_165_p3 = ap_pipeline_reg_pp0_iter9_tmp_4_reg_660;

assign normalized_V_addr_5_gep_fu_156_p3 = ap_pipeline_reg_pp0_iter9_tmp_4_reg_660;

assign normalized_V_addr_6_gep_fu_147_p3 = ap_pipeline_reg_pp0_iter9_tmp_4_reg_660;

assign normalized_V_addr_gep_fu_201_p3 = ap_pipeline_reg_pp0_iter9_tmp_4_reg_660;

assign op2_assign_1_cast_fu_439_p1 = $unsigned(tmp_18_fu_435_p1);

assign op2_assign_2_cast_fu_469_p1 = $unsigned(tmp_20_fu_465_p1);

assign op2_assign_3_cast_fu_506_p1 = tmp_21_fu_496_p4;

assign op2_assign_4_cast_fu_542_p1 = $unsigned(tmp_23_fu_538_p1);

assign op2_assign_5_cast_fu_561_p1 = tmp_24_fu_552_p4;

assign op2_assign_6_cast_fu_580_p1 = tmp_25_fu_571_p4;

assign op2_assign_cast6_fu_374_p1 = op2_assign_fu_367_p3;

assign op2_assign_cast_fu_378_p1 = op2_assign_fu_367_p3;

assign op2_assign_fu_367_p3 = {{tmp_5_reg_650}, {1'b0}};

assign p_shl1_cast_mid2_fu_314_p1 = p_shl1_cast_mid2_v_fu_307_p3;

assign p_shl1_cast_mid2_v_fu_307_p3 = {{ap_pipeline_reg_pp0_iter6_tmp_reg_618}, {ap_const_lv2_0}};

assign p_shl2_cast_fu_415_p1 = p_shl2_fu_408_p3;

assign p_shl2_fu_408_p3 = {{tmp_5_reg_650}, {ap_const_lv3_0}};

assign p_shl3_cast_fu_486_p1 = p_shl3_fu_479_p3;

assign p_shl3_fu_479_p3 = {{tmp_5_reg_650}, {ap_const_lv2_0}};

assign p_shl_cast_mid2_fu_330_p1 = p_shl_cast_mid2_v_fu_323_p3;

assign p_shl_cast_mid2_v_fu_323_p3 = {{ap_pipeline_reg_pp0_iter7_tmp_reg_618}, {ap_const_lv5_0}};

assign storemerge_cast_cast_fu_590_p3 = ((tmp_17_reg_705[0:0] === 1'b1) ? ap_const_lv10_33 : ap_const_lv10_0);

assign sum_address0 = tmp_mid2_fu_293_p1;

assign tmp1_cast_fu_344_p1 = tmp1_reg_639;

assign tmp1_fu_318_p2 = (ap_pipeline_reg_pp0_iter6_i_mid2_reg_607 + p_shl1_cast_mid2_fu_314_p1);

assign tmp_10_fu_473_p2 = (($signed(tmp_5_cast2_fu_394_p1) > $signed(op2_assign_2_cast_fu_469_p1)) ? 1'b1 : 1'b0);

assign tmp_11_fu_490_p2 = (p_shl3_cast_fu_486_p1 + average_cast7_fu_361_p1);

assign tmp_12_fu_510_p2 = (($signed(tmp_5_cast_fu_398_p1) > $signed(op2_assign_3_cast_fu_506_p1)) ? 1'b1 : 1'b0);

assign tmp_13_fu_516_p2 = (($signed(tmp_5_cast3_fu_390_p1) > $signed(average_cast_fu_364_p1)) ? 1'b1 : 1'b0);

assign tmp_14_fu_522_p2 = (p_shl3_cast_fu_486_p1 - average_cast7_fu_361_p1);

assign tmp_15_fu_546_p2 = (($signed(tmp_5_cast2_fu_394_p1) > $signed(op2_assign_4_cast_fu_542_p1)) ? 1'b1 : 1'b0);

assign tmp_16_fu_565_p2 = (($signed(tmp_5_cast4_fu_386_p1) > $signed(op2_assign_5_cast_fu_561_p1)) ? 1'b1 : 1'b0);

assign tmp_17_fu_584_p2 = (($signed(tmp_5_cast5_fu_382_p1) > $signed(op2_assign_6_cast_fu_580_p1)) ? 1'b1 : 1'b0);

assign tmp_18_fu_435_p1 = $signed(tmp_s_fu_425_p4);

assign tmp_19_fu_455_p4 = {{tmp_9_fu_449_p2[ap_const_lv32_1E : ap_const_lv32_2]}};

assign tmp_20_fu_465_p1 = $signed(tmp_19_fu_455_p4);

assign tmp_21_fu_496_p4 = {{tmp_11_fu_490_p2[ap_const_lv32_1D : ap_const_lv32_2]}};

assign tmp_22_fu_528_p4 = {{tmp_14_fu_522_p2[ap_const_lv32_1D : ap_const_lv32_2]}};

assign tmp_23_fu_538_p1 = $signed(tmp_22_fu_528_p4);

assign tmp_24_fu_552_p4 = {{mul_reg_644[ap_const_lv32_40 : ap_const_lv32_27]}};

assign tmp_25_fu_571_p4 = {{mul_reg_644[ap_const_lv32_40 : ap_const_lv32_28]}};

assign tmp_2_fu_255_p2 = ((i_reg_232 == ap_const_lv6_24) ? 1'b1 : 1'b0);

assign tmp_3_fu_347_p2 = (p_shl_cast_mid2_fu_330_p1 + tmp1_cast_fu_344_p1);

assign tmp_4_fu_353_p1 = tmp_3_fu_347_p2;

assign tmp_5_cast2_fu_394_p1 = $signed(descriptor_V_q0);

assign tmp_5_cast3_fu_390_p1 = $signed(descriptor_V_q0);

assign tmp_5_cast4_fu_386_p1 = $signed(descriptor_V_q0);

assign tmp_5_cast5_fu_382_p1 = $signed(descriptor_V_q0);

assign tmp_5_cast_fu_398_p1 = $signed(descriptor_V_q0);

assign tmp_6_fu_402_p2 = (($signed(tmp_5_cast_fu_398_p1) > $signed(op2_assign_cast_fu_378_p1)) ? 1'b1 : 1'b0);

assign tmp_7_fu_419_p2 = (p_shl2_cast_fu_415_p1 - average_cast8_fu_358_p1);

assign tmp_8_fu_443_p2 = (($signed(tmp_5_cast2_fu_394_p1) > $signed(op2_assign_1_cast_fu_439_p1)) ? 1'b1 : 1'b0);

assign tmp_9_fu_449_p2 = (p_shl2_cast_fu_415_p1 - op2_assign_cast6_fu_374_p1);

assign tmp_fu_283_p1 = tmp_mid2_v_fu_275_p3[0:0];

assign tmp_mid2_fu_293_p1 = tmp_mid2_v_reg_612;

assign tmp_mid2_v_fu_275_p3 = ((tmp_2_fu_255_p2[0:0] === 1'b1) ? blkIdx_s_fu_269_p2 : blkIdx_phi_fu_225_p4);

assign tmp_s_fu_425_p4 = {{tmp_7_fu_419_p2[ap_const_lv32_1E : ap_const_lv32_2]}};

always @ (posedge ap_clk) begin
    tmp_4_reg_660[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    ap_pipeline_reg_pp0_iter9_tmp_4_reg_660[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //normalizeHisto1
