// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CONTROL_BUS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of specs_r
//        bit 31~0 - specs_r[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of image0
//        bit 31~0 - image0[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of vector
//        bit 31~0 - vector[31:0] (Read/Write)
// 0x24 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XHOG_CONTROL_BUS_ADDR_AP_CTRL      0x00
#define XHOG_CONTROL_BUS_ADDR_GIE          0x04
#define XHOG_CONTROL_BUS_ADDR_IER          0x08
#define XHOG_CONTROL_BUS_ADDR_ISR          0x0c
#define XHOG_CONTROL_BUS_ADDR_SPECS_R_DATA 0x10
#define XHOG_CONTROL_BUS_BITS_SPECS_R_DATA 32
#define XHOG_CONTROL_BUS_ADDR_IMAGE0_DATA  0x18
#define XHOG_CONTROL_BUS_BITS_IMAGE0_DATA  32
#define XHOG_CONTROL_BUS_ADDR_VECTOR_DATA  0x20
#define XHOG_CONTROL_BUS_BITS_VECTOR_DATA  32

